using LiteQueue.Domain.Models;

namespace LiteQueue.Tests.Domain;

public class QueueMessageTests
{
    [Fact]
    public void NewMessage_HasAutoGeneratedId()
    {
        var message = new QueueMessage();
        Assert.NotEmpty(message.Id);
    }

    [Fact]
    public void NewMessage_HasUtcNowCreatedAt()
    {
        var before = DateTimeOffset.UtcNow.AddSeconds(-1);
        var message = new QueueMessage();
        var after = DateTimeOffset.UtcNow.AddSeconds(1);

        Assert.True(message.CreatedAt >= before);
        Assert.True(message.CreatedAt <= after);
    }

    [Fact]
    public void NewMessage_HasZeroDeliveryCount()
    {
        var message = new QueueMessage();
        Assert.Equal(0, message.DeliveryCount);
    }

    [Fact]
    public void NewMessage_HasEmptyBody()
    {
        var message = new QueueMessage();
        Assert.Equal(string.Empty, message.Body);
    }
}
