<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteQueue.Domain\LiteQueue.Domain.csproj" />
    <ProjectReference Include="..\LiteQueue.Contracts\LiteQueue.Contracts.csproj" />
  </ItemGroup>

</Project>
